version: '3'

services:
  db:
    image: postgres

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:5678
    volumes:
      - .:/app
    ports:
      - "5678:5678"
    depends_on:
      - db