# Generated by Django 2.0.3 on 2018-03-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Video'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='target_type',
            field=models.CharField(choices=[('P', 'Post'), ('V', 'Video')], max_length=1),
        ),
    ]
